.build-images: &build-images |
  set -x
  DIRS=""
  if [ "$CI_COMMIT_BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
    BASE_SHA=$CI_MERGE_REQUEST_DIFF_BASE_SHA
  else
    BASE_SHA=$CI_COMMIT_BEFORE_SHA
  fi
  CHANGED=$(for i in `git log --name-only --pretty=oneline --full-index $BASE_SHA..$CI_COMMIT_SHA | grep -vE '^[0-9a-f]{40} '`; do echo `dirname $i`; done | sort | uniq)
  for dir in $CHANGED; do
    case "$dir" in
      ".")
        ;;
      *)
        DIRS="$DIRS $dir"
        ;;
    esac
  done
  echo "Changed images: '$DIRS'"
  for d in $DIRS; do
    [ -d "$d" -a -f "$d/Dockerfile" ] || continue
    DATE=`date +'%Y%m%d%H%M%S'`
    docker build --build-arg CORES=`nproc` -t registry-mgmt.videolan.org/$d:$DATE $d/
    if [ "$CI_PROJECT_NAMESPACE" = "videolan" -a -z "$CI_MERGE_REQUEST_ID" ]; then
      docker login -u=$REGISTRY_LOGIN -p=$REGISTRY_AUTH registry-mgmt.videolan.org
      docker push registry-mgmt.videolan.org/$d:$DATE
      echo "Done: docker pull registry.videolan.org/$d:$DATE"
    fi
  done

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.12-dind

before_script:
  - docker info
  - apk add git

build:
  stage: build
  tags:
    - dind-amd64
  image:
    name: docker:20.10.12
  script:
    - *build-images
  only:
    refs:
      - merge_requests
      - master@videolan/docker-images
