.build-images: &build-images |
  set -x
  DIRS=""
  CHANGED=$(for i in `git log --name-only --pretty=oneline --full-index $CI_COMMIT_BEFORE_SHA..$CI_COMMIT_SHA | grep -vE '^[0-9a-f]{40} '`; do echo `dirname $i`; done | sort | uniq)
  for dir in $CHANGED; do
    case "$dir" in
      ".")
        ;;
      *)
        DIRS="$DIRS $dir"
        ;;
    esac
  done
  echo "Changed images: '$DIRS'"
  for d in $DIRS; do
    [ -d "$d" -a -f "$d/Dockerfile" ] || continue
    DATE=`date +'%Y%m%d%H%M%S'`
    docker build --build-arg CORES=`nproc` -t registry.videolan.org/$d:$DATE $d/
    docker push registry.videolan.org/$d:$DATE
  done

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.1-dind

before_script:
  - docker info
  - apk add git

build:
  stage: build
  image:
    name: docker:19.03.1
  script:
    - *build-images
