#!/bin/sh
#
# Import Martin's repository and do the needful (tm) to create a Dockerfile
# to use on VideoLAN jenkins.

set -ex

SED=sed
$SED --version >/dev/null 2>&1 || SED=gsed
$SED --version >/dev/null 2>&1 || (echo "GNU sed not found" && exit 1)

LLVM_MINGW_WBS_REPO=https://github.com/mstorsjo/llvm-mingw
LLVM_MINGW_WBS_COMMIT=e2c1dcac2b5cd7f81a937b1e065c894ad8d1d327
VIDEOLAN_BASE_TAG=20180215210000
SCRIPTS="build-all.sh build-llvm.sh install-wrappers.sh build-mingw-w64.sh build-compiler-rt.sh build-libcxx.sh merge-archives.sh strip-llvm.sh wrappers"
VIDEOLAN_IMAGE_DATE=201804070110

find . -not -name `basename "$0"` -delete

git clone $LLVM_MINGW_WBS_REPO
cd llvm-mingw
git reset --hard $LLVM_MINGW_WBS_COMMIT
cd ..

echo "# Autogenerated by ./gen-dockerfile.sh  You don't want to edit it, and all changes will be lost.\n#" > Dockerfile
$SED \
        -e "s,^FROM.*$,FROM registry.videolan.org:5000/videolan-base-xenial:$VIDEOLAN_BASE_TAG," \
        -e "/FROM.*/a\ \nENV IMAGE_DATE=$VIDEOLAN_IMAGE_DATE" \
        < llvm-mingw/Dockerfile >> Dockerfile
for i in $SCRIPTS; do
    cp -R llvm-mingw/$i .;
done
rm -rf llvm-mingw

# SF is mostly down these days.  Try our luck with a github mirror.
# Hopefully we will have the commit we need.
$SED \
        -i \
        -e "s,git://git.code.sf.net/p/mingw-w64/mingw-w64,https://github.com/mirror/mingw-w64," \
        build-mingw-w64.sh

echo "include ../common.mak" > Makefile

exit 0
