name: ci

on:
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - 'vlc-debian-llvm-ucrt/**'
  pull_request:
    paths:
      - 'vlc-debian-llvm-ucrt/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get image tag
        id: get-tag
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./vlc-debian-llvm-ucrt
          push: true
          tags: huynhsontung/vlc-debian-llvm-ucrt:${{ github.event_name != 'push' && 'artifact-' || '' }}${{ steps.get-tag.outputs.tag }}
